### ISSUE TITLE
MODULE NOT FOUND ERROR WITH OTHER ERRORS 

### ISSUE THREAD

**Issue by armaan12121121** [unofficialdxnny/Spotified#6]
**ERRORS I AM GETTING:**

![Screenshot 2024-01-23 143917](https://github.com/unofficialdxnny/Spotified/assets/157473793/6fb60fbe-0371-465f-8700-611dbf56d5a5)

Traceback (most recent call last):
  File "C:\Users\Komal Bhau\Desktop\Spotified-main\Spotified-main\follower.py", line 7, in <module>
    from selenium import webdriver
  File "C:\Users\Komal Bhau\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\__init__.py", line 29, in <module>
    from .firefox.firefox_profile import FirefoxProfile  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Komal Bhau\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\firefox\firefox_profile.py", line 31, in <module>
    from typing_extensions import deprecated
ModuleNotFoundError: No module named 'typing_extensions'
Press any key to continue . . .

**Comment by unofficialdxnny** [comment]
new version just released friend!
